---
apiVersion: aod/v1
kind: Environment
metadata:
  name: ravi-hq-all v3
spec:
  networking_type: unrestricted
  secrets:
    GITHUB_TOKEN: infisical:///dev/GITHUB_TOKEN
    HONEYCOMB_API_KEY: infisical:///dev/HONEYCOMB_API_KEY
    POSTHOG_API_KEY: infisical:///dev/POSTHOG_API_KEY
    RENDER_API_KEY: infisical:///dev/RENDER_API_KEY
